apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: tat-banking-demo
  labels:
    app: portal
    service: portal
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: portal
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-app
  namespace: tat-banking-demo
  labels:
    app: portal
    version: v1
spec:
  selector:
    matchLabels:
      app: portal
  replicas: 1
  template:
    metadata:
      labels:
        app: portal
        version: v1
    spec:
      containers:
      - name: portal
        image: quay.io/tonyfieit75/portal:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      imagePullSecrets:
        - name: tonyfieit75-pull-secret
